update workflows + delete actions folder

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -18,8 +18,8 @@ on:
         default: ''
 
   schedule:
-    - cron: '10 7 * * 1'
-    - cron: '10 8 * * 1'
+  - cron: '10 7 * * 1'
+  - cron: '10 8 * * 1'
 
 concurrency: trigger-release
 
@@ -51,44 +51,45 @@ jobs:
       uses: actions/checkout@v4
       with:
         token: ${{ secrets.WORKFLOW_USER_GH_TOKEN }}
+        fetch-depth: 0
 
     - name: Setup semver
-      uses: ./.github/actions/setup-semver
+      uses: sap/cs-actions/setup-semver@main
       with:
         version: ${{ env.SEMVER_VERSION }}
         install-directory: ${{ runner.temp }}/bin
 
     - name: Determine current release
       id: get_current_release
-      uses: ./.github/actions/get-highest-tag
+      uses: sap/cs-actions/get-highest-tag@main
       with:
         prefix: ${{ env.TAG_PREFIX }}
-
-    - name: Get number of commits since current release
-      id: commits
-      if: github.event_name == 'schedule'
-      run: |
-        git fetch --tags
-        echo "count=$(git rev-list --count --no-merges ${{ steps.get_current_release.outputs.tag }}..HEAD --before=1.hour)" >> $GITHUB_OUTPUT
 
     - name: Determine target release
       id: get_target_release
       run: |
         create_release=true
-        desired_version=${{ inputs.desired-version }}
-        current_version=${{ steps.get_current_release.outputs.version }}
 
-        if "${{ github.event_name == 'schedule' }}"; then
-          version_bump=patch
-          commits_count=${{ steps.commits.outputs.count }}
-
-          if [[ $commits_count -eq 0 ]]; then
+        if ${{ github.event_name == 'schedule' }}; then
+          commits_count=$(git rev-list --count --no-merges ${{ steps.get_current_release.outputs.tag }}..HEAD --before=1.hour)
+          if [ $commits_count -eq 0 ]; then
             create_release=false
-            >&2 echo "There are no commits since latest release found, nothing to do."
+            echo "There are no commits since latest release, nothing to do."
           fi
+          version_bump=patch
         else
           version_bump=${{ inputs.version-bump }}
         fi
+
+        echo "Create release: $create_release"
+        echo "create_release=$create_release" >> $GITHUB_OUTPUT
+
+        if [ "$create_release" != true ]; then
+          exit 0
+        fi
+
+        desired_version=${{ inputs.desired-version }}
+        current_version=${{ steps.get_current_release.outputs.version }}
 
         if [ -z "$desired_version" ]; then
           case $version_bump in
@@ -96,7 +97,7 @@ jobs:
               # ok
               ;;
             *)
-              >&2 echo "Invalid input: version-bump ($version_bump)."
+              >&2 echo "Invalid input: version-bump ($version_bump)"
               exit 1
           esac
           if [ -z "$current_version" ]; then
@@ -126,14 +127,12 @@ jobs:
 
         echo "Target version: $version"
         echo "Target tag: $tag"
-        echo "Create release: $create_release"
         echo "version=$version" >> $GITHUB_OUTPUT
         echo "tag=$tag" >> $GITHUB_OUTPUT
-        echo "create_release=$create_release" >> $GITHUB_OUTPUT
 
     - name: Determine target commit
-      if: steps.get_target_release.outputs.create_release == 'true'
       id: get_target_commit
+      if: steps.get_target_release.outputs.create_release == 'true'
       run: |
         sha=$(git rev-parse HEAD)
         echo "Target commit: $sha"
@@ -156,4 +155,3 @@ jobs:
       run: |
         gh release create ${{ steps.get_target_release.outputs.tag }} \
           --target "${{ steps.get_target_commit.outputs.sha }}"
-
